#!/bin/bash

docker run $@ --name=frontend-snapshot -it -v `pwd`:"/home/$(whoami)/PSEPSIS" -w "/home/$(whoami)/PSEPSIS" frontend-with-k-installed:latest -p 23232:23232 -p 23233:23233 -p 23234:23234 -p 23235:23235
